apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papra
  annotations:
    forecastle.stakater.com/appName: "Papra"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/papra-hq/papra/main/apps/web/public/logo-512.png"
