apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtarr
  annotations:
    forecastle.stakater.com/appName: "Youtarr"
    forecastle.stakater.com/group: "Media"
    forecastle.stakater.com/expose: "true"
