apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codex
  annotations:
    forecastle.stakater.com/appName: "Comics"
    forecastle.stakater.com/group: "Media"
    forecastle.stakater.com/expose: "true"
