apiVersion: v1
data:
  values.yaml: YWRkaXRpb25hbFZvbHVtZU1vdW50czoKLSBuYW1lOiB1c2ItemJ0MgogIG1vdW50UGF0aDogL2Rldi90dHlBQ00wCmFkZGl0aW9uYWxWb2x1bWVzOgotIG5hbWU6IHVzYi16YnQyCiAgaG9zdFBhdGg6CiAgICBwYXRoOiAvZGV2L3NlcmlhbC9ieS1pZC91c2ItTmFidV9DYXNhX1pCVC0yX0RDQjREOTBDMTQ2Qy1pZjAwCiAgICB0eXBlOiBDaGFyRGV2aWNlCg==
kind: Secret
metadata:
  name: home-assistant-values
  namespace: default
