---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- home-assistant-values.yaml
- paperless-values.yaml
- plex-values.yaml
- radarr-values.yaml
- resilio-values.yaml
- sonarr-values.yaml
