apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
spec:
  template:
    spec:
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
        - name: transcode-cache
          emptyDir: {}
      containers:
        # Tdarr Server (replaces generic 'container')
        - name: container
          image: ghcr.io/haveagitgat/tdarr
          imagePullPolicy: Always
          env:
            - name: TZ
              value: ${CLUSTER_TIME_ZONE}
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverIP
              value: 127.0.0.1
            - name: serverPort
              value: '8266'
            - name: webUIPort
              value: '8265'
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8265
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: tz-config
              readOnly: true
            - mountPath: /app/configs
              name: yasr-volume
              subPath: configs/tdarr
            - mountPath: /app/server
              name: yasr-volume
              subPath: configs/tdarr
            - mountPath: /media
              name: main-volume
              subPath: public
            - mountPath: /shared
              name: transcode-cache
          ports:
            - name: http
              containerPort: 8265
              protocol: TCP
            - name: server
              containerPort: 8266
              protocol: TCP
        # Tdarr Node
        - name: node
          image: haveagitgat/tdarr_node:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: ${CLUSTER_TIME_ZONE}
            - name: nodeID
              value: node
            - name: serverIP
              value: 127.0.0.1
            - name: serverPort
              value: '8266'
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 4000m
              memory: 4000Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: tz-config
              readOnly: true
            - mountPath: /app/configs
              name: yasr-volume
              subPath: configs/tdarr
            - mountPath: /media
              name: main-volume
              subPath: public
            - mountPath: /shared
              name: transcode-cache
