apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdarr
  annotations:
    forecastle.stakater.com/appName: "Tdarr"
    forecastle.stakater.com/group: "Media"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://home.tdarr.io/static/media/logo3-min.246d6df44c7f16ddebaf.png"
