apiVersion: v1
kind: Service
metadata:
  name: tdarr
spec:
  ports:
    - name: http
      port: 8265
      protocol: TCP
      targetPort: http
    - name: server
      port: 8266
      protocol: TCP
      targetPort: server
