apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tubesync
  annotations:
    forecastle.stakater.com/appName: "TubeSync"
    forecastle.stakater.com/group: "Media"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://github.com/meeb/tubesync/blob/main/tubesync/common/static/images/tubesync.png"
