apiVersion: v1
data:
  values.yaml: cGVyc2lzdGVuY2U6CiAgZGF0YToKICAgIGVuYWJsZWQ6IHRydWUKICAgIHR5cGU6IHB2YwogICAgZXhpc3RpbmdDbGFpbTogbWFpbi12b2x1bWUKICAgIHN1YlBhdGg6CiAgICAtIHBhdGg6IHB1YmxpYwogICAgICBtb3VudFBhdGg6IC9kYXRhCiAgICAtIHBhdGg6IGdhbmRhemd1bC9QaWN0dXJlcwogICAgICBtb3VudFBhdGg6IC9waWN0dXJlcwogICAgLSBwYXRoOiByZW5lcG9yL1BJQ1RVUkVTCiAgICAgIG1vdW50UGF0aDogL3JlbmVfcGljdHVyZXMK
kind: Secret
metadata:
  name: plex-values
  namespace: default
