apiVersion: v1
data:
  values.yaml: cGVyc2lzdGVuY2U6CiAgZXh0cmFNb3VudHM6CiAgLSBuYW1lOiBkYXRhCiAgICBtb3VudFBhdGg6IHBpY3R1cmVzCiAgICBzdWJQYXRoOiAiZ2FuZGF6Z3VsL1BpY3R1cmVzIgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: plex-values
  namespace: default
