apiVersion: v1
data:
  values.yaml: cGVyc2lzdGVuY2U6CiAgbW92aWVzOgogICAgZW5hYmxlZDogdHJ1ZQogICAgdHlwZTogcHZjCiAgICBleGlzdGluZ0NsYWltOiBtYWluLXZvbHVtZQogICAgc3ViUGF0aDogcHVibGljL01vdmllcwo=
kind: Secret
metadata:
  name: radarr-values
  namespace: default
