apiVersion: v1
data:
  values.yaml: cGVyc2lzdGVuY2U6CiAgY29uZmlnOgogICAgZW5hYmxlZDogdHJ1ZQogICAgZXhpc3RpbmdDbGFpbTogeWFzci12b2x1bWUKICAgIG1vdW50UGF0aDogL2NvbmZpZwogICAgc3ViUGF0aDogY29uZmlncy9yZXNpbGlvCiAgc3luYzoKICAgIGVuYWJsZWQ6IHRydWUKICAgIGV4aXN0aW5nQ2xhaW06IG1haW4tdm9sdW1lCiAgICBtb3VudFBhdGg6IC9zeW5jCiAgICBzdWJQYXRoOiBidHN5bmMK
kind: Secret
metadata:
  name: resilio-values
  namespace: default
