apiVersion: v1
data:
  values.yaml: c29uYXJyOgogIHZvbHVtZU1vdW50czoKICAtIG5hbWU6IHlhc3Itdm9sdW1lCiAgICBtb3VudFBhdGg6IC9jb25maWcKICAgIHN1YlBhdGg6IGNvbmZpZ3Mvc29uYXJyCiAgLSBuYW1lOiB5YXNyLXZvbHVtZQogICAgbW91bnRQYXRoOiAvZGF0YQogICAgc3ViUGF0aDogY29uZmlncy90cmFuc21pc3Npb24KICAtIG5hbWU6IG1haW4tdm9sdW1lCiAgICBtb3VudFBhdGg6IC90dgogICAgc3ViUGF0aDogcHVibGljL1RWCgpyYWRhcnI6CiAgdm9sdW1lTW91bnRzOgogIC0gbmFtZTogeWFzci12b2x1bWUKICAgIG1vdW50UGF0aDogL2NvbmZpZwogICAgc3ViUGF0aDogY29uZmlncy9yYWRhcnIKICAtIG5hbWU6IHlhc3Itdm9sdW1lCiAgICBtb3VudFBhdGg6IC9kYXRhCiAgICBzdWJQYXRoOiBjb25maWdzL3RyYW5zbWlzc2lvbgogIC0gbmFtZTogbWFpbi12b2x1bWUKICAgIG1vdW50UGF0aDogL21vdmllcwogICAgc3ViUGF0aDogcHVibGljL01vdmllcwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seedbox-values
  namespace: default
