apiVersion: v1
data:
  values.yaml: cGVyc2lzdGVuY2U6CiAgdHY6CiAgICBlbmFibGVkOiB0cnVlCiAgICB0eXBlOiBwdmMKICAgIGV4aXN0aW5nQ2xhaW06IG1haW4tdm9sdW1lCiAgICBzdWJQYXRoOiBwdWJsaWMvVFYK
kind: Secret
metadata:
  name: sonarr-values
  namespace: default
