---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets/
  - ./RsyncCronJobs.yaml
  - ./ImmichBackupCronJob.yaml
  - ../../../apps/ActualBudget.yaml
  - ../../../apps/Bitwarden.yaml
  - ../../../apps/Forecastle.yaml
  - ../../../apps/Headlamp.yaml
  - ../../../apps/HomeAssistant.yaml
  - ../../../apps/Paperless.yaml
  - ../../../apps/Resilio.yaml
  - ../../../apps/SFTPGo.yaml
  - ../../../apps/ZWaveJS.yaml
  - ../../../apps/Mealie.yaml
  - ../../../apps/AudioBookShelf.yaml
  - ../../../apps/Codex.yaml
  - ../../../apps/Transmission.yaml
  - ../../../apps/Lidarr.yaml
  - ../../../apps/Overseerr.yaml
  - ../../../apps/Prowlarr.yaml
  - ../../../apps/Radarr.yaml
  - ../../../apps/Sonarr.yaml
  - ../../../apps/TubeSync.yaml
  - ../../../apps/Tdarr.yaml
  - ../../../apps/Plex.yaml
  - ../../../apps/RDiffWeb.yaml
  - ../../../apps/Harbor.yaml
  - ../../../apps/Qdrant.yaml
  - ../../../apps/Immich.yaml
