additionalVolumeMounts:
- name: usb-zbt2
  mountPath: /dev/ttyACM0
additionalVolumes:
- name: usb-zbt2
  hostPath:
    path: /dev/serial/by-id/usb-Nabu_Casa_ZBT-2_DCB4D90C146C-if00
    type: CharDevice
