---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./secrets/
- ../../../apps/K8sDashboard.yaml
- ../../../apps/Plex.yaml
- ../../../apps/Resilio.yaml
- ../../../apps/Bitwarden.yaml
- ../../../apps/HomeAssistant.yaml
#- ../../../apps/MQTTBroker.yaml
#- ../../../apps/transmission/rafag/
#- ../../../apps/Radarr.yaml
#- ../../../apps/Sonarr.yaml
#- ../../../apps/Prowlarr.yaml
- ../../../apps/Photoprism.yaml
- ../../../apps/Zigbee2mqtt.yaml
- ../../../apps/Paperless.yaml
- ../../../apps/SFTPGo.yaml
- ../../../apps/MosquitoMQTTBroker.yaml
- ../../../apps/Forecastle.yaml
- ../../../apps/WeaveGitopsDashboard.yaml
